name: Build ActivityPub Multi-Arch Images

on:
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:


jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout empty repo
      uses: actions/checkout@v5

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Alpine Networking Tester Multi-Arch Image
      run: |
        docker buildx create --use --name mybuilder || true

        DATE=$(date +'%Y-%m-%d')

        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          --tag ghcr.io/404-not-found-dev/alpine-networking-tester:latest \
          --tag ghcr.io/404-not-found-dev/alpine-networking-tester:${DATE} \
          ./alpine-networking-tester
