name: Build Alpine Networking Tester Multi-Arch Images

on:
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:


jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout empty repo
      uses: actions/checkout@v5

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Meta (Tags & Labels with date)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/404-not-found-dev/alpine-networking-tester
        tags: |
          type=raw,value=latest
          type=raw,value={{date 'YYYY-MM-DD' tz='Europe/Berlin'}}


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./alpine-networking-tester
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
